import { useState } from 'react';
import { monthlyPayment } from '../lib/safPayment';

export function SafPurchaseOptions({onConsult}:{onConsult:()=>void}) {
  const [mode,setMode]=useState('mortgage');
  const [price,setPrice]=useState(''),[deposit,setDeposit]=useState(''),[rate,setRate]=useState(''),[years,setYears]=useState('');
  const payment=[price,deposit,rate,years].every(v=>v.trim()!=='')?monthlyPayment(Number(price),Number(deposit),Number(rate),Number(years)):null;
  return <section className="saf-purchase-options" id="saf-payment"><h2>Как купить</h2><div className="saf-purchase-tabs" role="tablist" aria-label="Способ покупки">{[['mortgage','Ипотека'],['full','Оплата 100%'],['installment','Рассрочка']].map(([key,label],index)=><button key={key} type="button" role="tab" aria-selected={mode===key} tabIndex={mode===key?0:-1} onClick={()=>setMode(key)} onKeyDown={event=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();const next=(index+(event.key==='ArrowRight'?1:2))%3;setMode(['mortgage','full','installment'][next]);(event.currentTarget.parentElement?.children[next] as HTMLButtonElement)?.focus();}}}>{label}</button>)}</div>
    <div role="tabpanel">{mode==='mortgage'?<><p>Введите согласованные с банком параметры. Расчёт ориентировочный, без комиссий и страхования; он не является предложением банка.</p><div className="saf-payment-fields"><label>Стоимость квартиры, ₸<input type="number" min="1" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Уточните стоимость"/></label><label>Первый взнос, ₸<input type="number" min="0" value={deposit} onChange={e=>setDeposit(e.target.value)}/></label><label>Ставка, % годовых<input type="number" min="0" max="100" step="0.1" value={rate} onChange={e=>setRate(e.target.value)}/></label><label>Срок, лет<input type="number" min="1" max="50" value={years} onChange={e=>setYears(e.target.value)}/></label></div><output aria-live="polite">{payment===null?'Заполните параметры для расчёта':`Ориентировочно ${Math.round(payment).toLocaleString('ru-RU')} ₸ / месяц`}</output></>:<p>{mode==='full'?'Актуальную стоимость при полной оплате и возможные скидки уточнит отдел продаж.':'Размер первого взноса, срок и график рассрочки необходимо согласовать с отделом продаж.'}</p>}<button type="button" className="saf-purchase-consult" onClick={onConsult}>Получить консультацию</button></div>
  </section>;
}
