import {siteUrl} from '../lib/site';
import {PanoramaViewer} from './PanoramaViewer';
import React,{useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RotateCcw,Maximize,Plus,Minus,Navigation,Sun,Moon,ArrowUpRight} from 'lucide-react';
import {ExperienceConfig,Panorama} from '../lib/experience';
interface SceneProps{config:ExperienceConfig;section:number;floor:number;onSelect?:(section:number,floor:number)=>void;interior?:boolean}
export function SceneViewer({config,section,floor,onSelect,interior=false}:SceneProps){
 const host=useRef<HTMLDivElement>(null);const wrap=useRef<HTMLDivElement>(null);const api=useRef<{camera:THREE.PerspectiveCamera;controls:OrbitControls;scene:THREE.Scene;light:THREE.DirectionalLight}|null>(null);const selection=useRef({section,floor});selection.current={section,floor};const selectRef=useRef(onSelect);selectRef.current=onSelect;const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [night,setNight]=useState(false);const [spot,setSpot]=useState('Общий вид');
 useEffect(()=>{const el=host.current;if(!el)return;setError('');let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});}catch{setError('3D недоступно в этом браузере. Выберите секцию и этаж кнопками ниже.');return;}
 let stopped=false;const scene=new THREE.Scene();scene.background=new THREE.Color('#e9edf4');scene.fog=new THREE.Fog('#e9edf4',120,300);const camera=new THREE.PerspectiveCamera(42,1,.1,500);camera.position.set(66,48,68);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,10,0);controls.enableDamping=true;controls.minDistance=8;controls.maxDistance=140;controls.maxPolarAngle=Math.PI*.48;renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Интерактивная 3D-сцена: вращайте перетаскиванием, масштабируйте колесом');renderer.domElement.setAttribute('role','img');
 scene.add(new THREE.HemisphereLight('#eff5ff','#817c68',2));const light=new THREE.DirectionalLight('#ffefcf',3);light.position.set(35,65,35);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-65,right:65,top:65,bottom:-65,far:160});scene.add(light);api.current={camera,controls,scene,light};
 const model=new THREE.Group();scene.add(model);const pickables:THREE.Mesh[]=[];const floors:THREE.Mesh[]=[];const mat=(color:string,roughness=.7)=>new THREE.MeshStandardMaterial({color,roughness});const stone=mat('#e3ddce'),trim=mat('#b6a990'),glass=mat('#4b6575',.25),ground=mat('#d1d5ce'),grass=mat('#799371'),wood=mat('#997653'),leaf=mat('#597d55');
 function box(w:number,h:number,d:number,x:number,y:number,z:number,m:THREE.Material,parent:THREE.Object3D=model){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
 if(!interior)box(105,.6,85,0,-.5,0,ground);box(42,.2,35,0,0,18,grass);box(35,.25,4,0,.15,10,trim);box(4,.25,32,0,.15,14,trim);
 if(!interior){for(let s=1;s<=2;s++){const sx=s===1?-18:18;const sz=s===1?-7:-13;for(let f=1;f<=9;f++){const floorMat=stone.clone();const slab=box(24,3.1,16,sx,(f-1)*3.2+1.6,sz,floorMat);slab.userData={section:s,floor:f};floors.push(slab);pickables.push(slab);box(24.7,.22,16.7,sx,f*3.2,sz,trim);for(let k=0;k<6;k++){box(2.65,2.45,.12,sx-10+k*4,(f-1)*3.2+1.7,sz+8.08,glass).userData={section:s,floor:f};box(2.65,2.45,.12,sx-10+k*4,(f-1)*3.2+1.7,sz-8.08,glass);}for(let k=0;k<4;k++)box(.12,2.45,2.5,sx+12.08,(f-1)*3.2+1.7,sz-6+k*4,glass);}box(25,.65,17,sx,29.2,sz,trim);box(5,2.8,.4,sx,1.5,sz+8.3,glass);}for(let k=0;k<18;k++){const a=k*Math.PI*2/18;const x=Math.cos(a)*36,z=18+Math.sin(a)*19;box(.45,2.6,.45,x,1.3,z,wood);const tree=new THREE.Mesh(new THREE.IcosahedronGeometry(2.4,1),leaf);tree.position.set(x,4,z);tree.castShadow=true;model.add(tree);}for(let i=0;i<5;i++){box(4,.4,1,-12+i*6,.6,28,wood);box(.25,.8,1,-13+i*6,.3,28,trim);box(.25,.8,1,-11+i*6,.3,28,trim);}box(8,.15,8,10,.25,17,mat('#d0bb87'));
 }else{model.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose();});model.clear();box(14,.25,11,0,-.2,0,mat('#c8baa5'));box(14,3,.2,0,1.5,-5.5,stone);box(.2,3,11,-7,1.5,0,stone);box(.2,3,11,7,1.5,0,stone);box(5,1,.2,-4.5,.5,5.5,stone);box(5,1,.2,4.5,.5,5.5,stone);box(4,2.4,.1,-4,1.8,-5.35,glass);box(4,2.4,.1,4,1.8,-5.35,glass);box(.2,2.7,6,1,1.35,-2.5,stone);box(6,2.7,.2,4,1.35,.5,stone);box(4,1,1.5,-3,.5,1,mat('#d6d2c9'));box(4,.7,.3,-3,1.1,1.6,mat('#d6d2c9'));box(2,.45,1.2,-3,.2,-1,wood);box(3,.55,4,4,.3,-2.5,wood);box(2.8,.2,3.8,4,.7,-2.5,mat('#f1eee4'));box(2.8,.35,1,4,.95,-4,mat('#fffaf0'));box(1,.9,4,-6,.45,-2.5,trim);camera.position.set(15,13,18);controls.target.set(0,0,0);controls.minDistance=3;controls.maxDistance=45;}
 if(config.model.url&&!interior){setLoading(true);new GLTFLoader().load(siteUrl(config.model.url),gltf=>{if(stopped){gltf.scene.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose();});return;}model.visible=false;scene.remove(model);const root=gltf.scene;root.scale.setScalar(config.model.scale||1);const bounds=new THREE.Box3().setFromObject(root);const center=bounds.getCenter(new THREE.Vector3());root.position.sub(center);root.position.y+=bounds.getSize(new THREE.Vector3()).y/2;root.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;const hit=/section[_ -]?(\d+).*floor[_ -]?(\d+)/i.exec(o.name);if(hit)o.userData={section:Number(hit[1]),floor:Number(hit[2])};}});scene.add(root);setLoading(false);},undefined,()=>{if(!stopped){setLoading(false);setError('Модель не загрузилась. Показана демонстрационная сцена.');}});}
 const raycaster=new THREE.Raycaster();let down=[0,0];const pointerDown=(e:PointerEvent)=>{down=[e.clientX,e.clientY];};const pointerUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=raycaster.intersectObjects(scene.children,true).find(h=>h.object.userData.section);if(hit)selectRef.current?.(hit.object.userData.section,hit.object.userData.floor);};renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',pointerUp);
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;if(w&&h){renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}};const observer=new ResizeObserver(resize);observer.observe(el);resize();renderer.setAnimationLoop(()=>{if(stopped)return;floors.forEach(o=>{const chosen=o.userData.section===selection.current.section&&o.userData.floor===selection.current.floor;const m=o.material as THREE.MeshStandardMaterial;m.color.set(chosen?'#7776ce':'#e3ddce');m.emissive.set(chosen?'#171744':'#000000');});controls.update();renderer.render(scene,camera);});
 return()=>{stopped=true;observer.disconnect();renderer.setAnimationLoop(null);renderer.domElement.removeEventListener('pointerdown',pointerDown);renderer.domElement.removeEventListener('pointerup',pointerUp);controls.dispose();const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>();scene.traverse(o=>{if(o instanceof THREE.Mesh){geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));}});model.traverse(o=>{if(o instanceof THREE.Mesh){geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>{Object.values(m).forEach(v=>{if(v instanceof THREE.Texture)v.dispose();});m.dispose();});renderer.dispose();renderer.domElement.remove();api.current=null;};
 },[config.model.url,config.model.scale,interior]);
 const view=(label:string,p:number[],t:number[])=>{const a=api.current;if(!a)return;a.camera.position.set(...p as [number,number,number]);a.controls.target.set(...t as [number,number,number]);a.controls.update();setSpot(label);};
 const fullscreen=()=>{if(document.fullscreenElement)document.exitFullscreen();else wrap.current?.requestFullscreen().catch(()=>setError('Полноэкранный режим недоступен в этом браузере.'));};
 return <div className="scene-wrap" ref={wrap}><div className="scene-canvas" ref={host}/><div className="scene-label"><span className="live-dot"/>{config.model.url&&!error&&!interior?config.model.label:interior?'Демо-интерьер · не проект отделки':'Демо-сцена · не точная модель Shattyq'}</div><div className="scene-tools"><button className="icon" aria-label="Приблизить 3D" onClick={()=>{const a=api.current;if(a){a.camera.position.lerp(a.controls.target,.15);a.controls.update();}}}><Plus/></button><button className="icon" aria-label="Отдалить 3D" onClick={()=>{const a=api.current;if(a){a.camera.position.sub(a.controls.target).multiplyScalar(1.15).add(a.controls.target);a.controls.update();}}}><Minus/></button><button className="icon" aria-label="Сбросить ракурс" onClick={()=>view('Общий вид',interior?[15,13,18]:[66,48,68],interior?[0,0,0]:[0,10,0])}><RotateCcw/></button><button className="icon" aria-label="Сменить освещение" onClick={()=>{const a=api.current;if(a){a.scene.background=new THREE.Color(night?'#e9edf4':'#242940');a.scene.fog=new THREE.Fog(night?'#e9edf4':'#242940',120,300);a.light.intensity=night?3:.4;setNight(!night);}}}>{night?<Sun/>:<Moon/>}</button><button className="icon" aria-label="На весь экран" onClick={fullscreen}><Maximize/></button></div><div className="scene-presets">{(interior?[['Общий вид',[15,13,18],[0,0,0]],['Гостиная',[-3,1.65,4],[-3,1.65,-3]],['Спальня',[4,1.65,0],[4,1.65,-4]]]:[['Общий вид',[66,48,68],[0,10,0]],['Во дворе',[0,3,30],[0,9,-10]],['У входа',[-18,2,12],[-18,3,-7]],['Вид сверху',[0,92,1],[0,0,0]]]).map(([title,p,t])=><button key={title as string} className={spot===title?'active':''} onClick={()=>view(title as string,p as number[],t as number[])}><Navigation size={13}/>{title as string}</button>)}</div>{loading&&<div className="scene-notice" role="status">Загрузка модели…</div>}{error&&<div className="scene-notice" role="status">{error}</div>}<span className="scene-hint">Вращайте мышью или пальцем · Колесо / жест для масштаба</span></div>;
}
export function TourPage({config}:{config:ExperienceConfig}){const [mode,setMode]=useState('complex');return <div className="experience-page"><div className="page-heading"><span className="eyebrow">SHATTYQ / ВИРТУАЛЬНЫЙ ТУР</span><h1>Посмотрите вокруг.<br/>Почувствуйте пространство.</h1><p>Свободное вращение, смена точек обзора и освещения. Пока используются демонстрационные объёмы; исходная модель и панорамы проекта будут подключены позднее.</p></div><div className="tabs feature-tabs"><button className={mode==='complex'?'active':''} onClick={()=>setMode('complex')}>Территория в 3D</button><button className={mode==='interior'?'active':''} onClick={()=>setMode('interior')}>Демо-интерьер</button>{config.panoramas.length>0&&<button className={mode==='panorama'?'active':''} onClick={()=>setMode('panorama')}>Панорамы 360°</button>}</div>{mode==='panorama'?<PanoramaViewer panoramas={config.panoramas}/>:<SceneViewer key={mode} config={config} section={0} floor={0} interior={mode==='interior'}/>}<div className="feature-bottom"><p>Рендеры самого Shattyq смотрите в галерее. Демо-сцена показывает возможности будущего тура и не описывает реальные размеры или комплектацию.</p><a className="button blue" href={siteUrl("/visual")}>Выбрать квартиру на 3D-плане <ArrowUpRight size={18}/></a></div></div>;}

