import { expect, test } from '@playwright/test';

test('numbered apartment keeps its identity across all four views, reload, history and constructor', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${new URL(response.url()).pathname}`); });
  await page.goto('/saf/visual/block/1/floor/2');
  await page.getByRole('link', { name: /№ 1 · 2-комнатная/ }).click();
  await expect(page).toHaveURL(/\/saf\/apartment\/saf-observation-1-2-property-1$/);
  await expect(page.getByRole('heading', { name: '2-комнатная № 1' })).toBeVisible();
  await expect(page.locator('.saf-apartment-summary')).toContainText('80,58');
  await page.getByRole('tab', { name: 'Планировка', exact: true }).click();
  await expect(page.getByRole('img', { name: 'Планировка квартиры № 1', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Увеличить план', exact: true }).click();
  await expect(page.getByRole('button', { name: '150%', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'На этаже', exact: true }).click();
  await expect(page.locator('.saf-sheet-caption')).toContainText('Приблизительная привязка квартир для прототипа');
  await page.getByRole('button', { name: 'Увеличить схему', exact: true }).click();
  await expect(page.getByRole('button', { name: '150%', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('tab', { name: 'На этаже', exact: true })).toHaveAttribute('aria-selected', 'true');
  await page.getByRole('tab', { name: 'На генплане', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Секция 1, 54 квартир в снимке' })).toHaveAttribute('aria-pressed', 'true');
  await page.goBack();
  await expect(page.getByRole('tab', { name: 'На этаже', exact: true })).toHaveAttribute('aria-selected', 'true');
  await page.getByRole('tab', { name: '3D-тур', exact: true }).click();
  await expect(page.locator('.saf-apartment-tour canvas')).toBeVisible();
  await page.getByRole('button', { name: 'Интерьер', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Сохранить на устройстве' })).toBeVisible();
  await page.getByRole('button', { name: 'Сохранить на устройстве' }).click();
  await page.getByRole('tab', { name: 'Планировка', exact: true }).click();
  await expect(page.locator('.interior-editor')).toBeHidden();
  await page.getByRole('tab', { name: 'Планировка', exact: true }).focus();
  await page.keyboard.press('ArrowRight');
  await expect(page.getByRole('tab', { name: 'На этаже', exact: true })).toBeFocused();
  const download = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Скачать план' }).click();
  expect((await download).suggestedFilename()).toBe('SAF-1-1.png');
  await page.getByRole('link', { name: 'К квартирам этажа' }).click();
  await expect(page).toHaveURL(/\/block\/1\/floor\/2$/);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 2)).toBe(true);
  expect(errors).toEqual([]);
});

test('all floor units can open even when their layout image is missing', async ({ page }) => {
  await page.goto('/saf/visual/block/1/floor/4');
  await expect(page.locator('.saf-unit-choice')).toHaveCount(5);
  const hrefs = await page.locator('.saf-unit-choice').evaluateAll(links => links.map(link => link.getAttribute('href')));
  expect(hrefs.length).toBe(5);
  expect(hrefs.every(href => href?.startsWith('/saf/apartment/'))).toBe(true);
  await page.getByRole('link', { name: /№ 14 · 2-комнатная/ }).click();
  const heading = await page.locator('h1').textContent();
  await page.reload();
  await expect(page.locator('h1')).toHaveText(heading!);
  await expect(page.locator('.saf-apartment-summary')).toContainText('4 из 12');
  await page.getByRole('tab', { name: 'Планировка', exact: true }).click();
  await expect(page.getByText('Изображение этой квартиры не опубликовано.', { exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Скачать план' })).toHaveCount(0);
  await page.goto('/saf/apartment/not-a-unit');
  await expect(page.getByRole('heading', { name: 'Страница не найдена.' })).toBeVisible();
});
