import {siteUrl,sitePath} from './lib/site';
import React, { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUpRight, ArrowRight, ArrowLeft, MapPin, Phone, Menu, X, Heart, Expand, Download, Building2, Trees, ShieldCheck, ScanFace, LayoutGrid, Monitor, Globe, ChevronLeft, ChevronRight, Home, Info } from 'lucide-react';
import data from './data/shattyq.json';
import './styles/sensata.css';
import './styles/experience.css';
import { ExperienceRoutes, HomeExperiences, projectLinks } from './features/ExperienceRoutes';
import { LeadForm } from './features/LeadForm';
import { useExperience } from './lib/useExperience';

type Plan = typeof data.plans[number];
type Gallery = 'Архитектура' | 'Благоустройство' | 'Холлы';
const galleries: Record<Gallery, string[]> = {
  'Архитектура': ['/sensata/hero.jpg', '/sensata/architecture.jpg'],
  'Благоустройство': Array.from({length:11},(_,i)=>`/sensata/courtyard-${i+1}.jpg`),
  'Холлы': Array.from({length:13},(_,i)=>`/sensata/lobby-${i+1}.jpg`),
};
const nav = [['about','О проекте'],['gallery','Галерея'],['layouts','Планировки'],['location','Локация']];
const address = 'Астана, район Есиль · Ә. Бөкейхана / Орынбор';
const mapLink = 'https://2gis.kz/astana/search/'+encodeURIComponent('Shattyq жилой комплекс');
function readFavorites(): string[] { try { const v=JSON.parse(localStorage.getItem('sensata-shattyq-favorites')||'[]'); return Array.isArray(v)?v.filter((id:unknown)=>typeof id==='string'&&data.plans.some(p=>p.id===id)):[]; } catch {return [];} }
function Modal({children,close,label,wide=false}:{children:React.ReactNode;close:()=>void;label:string;wide?:boolean}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{ref.current?.showModal(); const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[]);
  return <dialog ref={ref} className={`modal ${wide?'wide':''}`} aria-label={label} onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close();}}><button className="icon modal-close" onClick={close} aria-label="Закрыть"><X/></button>{children}</dialog>;
}
export default function App(){
  const [mode,setMode]=useState<'web'|'kiosk'>(()=>new URLSearchParams(location.search).get('mode')==='kiosk'?'kiosk':'web');
  const [menu,setMenu]=useState(false);
  const {config,inventory,warning}=useExperience();
  const [contactTopic,setContactTopic]=useState('Консультация по Shattyq');
  const isHome=sitePath()==='/'||sitePath()==='/index.html';
  const consult=(topic:string)=>{setContactTopic(topic);setContact(true);};
  useEffect(()=>{if(!isHome)document.title='Shattyq · '+(projectLinks.find(([url])=>url===sitePath())?.[1]||'Выбор квартиры')+' | Sensata Group';},[isHome]);
  const [room,setRoom]=useState(0);
  const [expanded,setExpanded]=useState(false);
  const [favorites,setFavorites]=useState<string[]>(readFavorites);
  const [onlyFavorites,setOnlyFavorites]=useState(false);
  const [selected,setSelected]=useState<Plan|null>(null);
  const [contact,setContact]=useState(false);
  const [gallery,setGallery]=useState<Gallery>('Архитектура');
  const [slide,setSlide]=useState(0);
  const [lightbox,setLightbox]=useState(false);
  const [section,setSection]=useState('overview');
  const [zoom,setZoom]=useState(false);
  const shown=data.plans.filter(p=>(!room||p.rooms===room)&&(!onlyFavorites||favorites.includes(p.id)));
  useEffect(()=>{try{localStorage.setItem('sensata-shattyq-favorites',JSON.stringify(favorites));}catch{}},[favorites]);
  const favorite=(id:string)=>setFavorites(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
  const changeGallery=(g:Gallery)=>{setGallery(g);setSlide(0);};
  const next=(d:number)=>setSlide(v=>(v+d+galleries[gallery].length)%galleries[gallery].length);
  const changeMode=()=>{const m=mode==='web'?'kiosk':'web';setMode(m);setMenu(false);const url=new URL(location.href);url.searchParams.set('mode',m);history.replaceState(null,'',url);window.scrollTo(0,0);};
  const goPlans=()=>{if(mode==='web'){location.assign(siteUrl('/parametric-search'));return;}setOnlyFavorites(false);setRoom(0);if(mode==='kiosk')setSection('layouts');else document.getElementById('layouts')?.scrollIntoView({behavior:'smooth'});};
  const showFavorites=()=>{if(mode==='web'){location.assign(siteUrl('/favorite'));return;}setOnlyFavorites(true);setRoom(0);setExpanded(true);if(mode==='kiosk')setSection('layouts');else document.getElementById('layouts')?.scrollIntoView({behavior:'smooth'});};
  const galleryView=<><div className="gallery-controls"><div className="tabs">{(Object.keys(galleries) as Gallery[]).map(g=><button key={g} className={gallery===g?'active':''} aria-pressed={gallery===g} onClick={()=>changeGallery(g)}>{g}</button>)}</div><div className="arrows"><span>{String(slide+1).padStart(2,'0')} / {String(galleries[gallery].length).padStart(2,'0')}</span><button className="icon" aria-label="Предыдущее фото" onClick={()=>next(-1)}><ChevronLeft/></button><button className="icon" aria-label="Следующее фото" onClick={()=>next(1)}><ChevronRight/></button></div></div><button className={`gallery-image ${gallery==='Холлы'?'portrait':''}`} onClick={()=>setLightbox(true)} aria-label="Открыть фото на весь экран"><img src={siteUrl(galleries[gallery][slide])} alt={`Shattyq — ${gallery.toLowerCase()}, вид ${slide+1}`}/><span className="image-expand"><Expand size={19}/></span><span className="image-caption">SHATTYQ / {gallery}</span></button></>;
  const plansView=<><div className="plan-toolbar"><div className="tabs" aria-label="Количество комнат">{[0,2,3,4].map(n=><button key={n} className={room===n?'active':''} aria-pressed={room===n} onClick={()=>{setRoom(n);setExpanded(false);}}>{n?`${n}-комнатные`:'Все планировки'}</button>)}</div><button className={`favorite-filter ${onlyFavorites?'selected':''}`} onClick={()=>{setOnlyFavorites(v=>!v);setExpanded(true);}}><Heart size={17} fill={onlyFavorites?'currentColor':'none'}/> Избранное ({favorites.length})</button></div><div className="results-line"><span>{shown.length} {shown.length===1?'планировка':shown.length>1&&shown.length<5?'планировки':'планировок'} · 1 очередь</span><span>Стоимость и наличие — в отделе продаж</span></div><div className="plan-grid">{(expanded?shown:shown.slice(0,6)).map(p=><article className="plan-card" key={p.id}><div className="plan-top"><span>{p.rooms}-комнатная</span><button className={`icon ${favorites.includes(p.id)?'saved':''}`} aria-label={`${favorites.includes(p.id)?'Удалить из избранного':'В избранное'}: планировка ${p.id.split('-')[1]}`} onClick={()=>favorite(p.id)}><Heart size={20} fill={favorites.includes(p.id)?'currentColor':'none'}/></button></div><button className="plan-image" onClick={()=>{setSelected(p);setZoom(false);}} aria-label={`Открыть планировку ${p.id.split('-')[1]}`}><img src={siteUrl(p.image)} loading="lazy" alt={`${p.rooms}-комнатная планировка Shattyq, вариант ${p.id.split('-')[1]}`}/></button><div className="plan-bottom"><div><small>Вариант {p.id.split('-')[1]?.padStart(2,'0')}</small><strong>Цена по запросу</strong></div><button className="icon" onClick={()=>{setSelected(p);setZoom(false);}} aria-label={`Подробнее о планировке ${p.id.split('-')[1]}`}><ArrowUpRight/></button></div></article>)}</div>{shown.length===0&&<div className="empty"><Heart size={34}/><h3>Здесь будут ваши планировки</h3><p>Нажмите на сердечко у понравившегося варианта.</p><button className="button blue" onClick={()=>{setOnlyFavorites(false);setRoom(0);}}>Все планировки <ArrowRight size={18}/></button></div>}{!expanded&&shown.length>6&&<button className="button outline more" onClick={()=>setExpanded(true)}>Показать все {shown.length} планировок <ArrowDown size={17}/></button>}</>;
  const locationView=<div className="location-grid"><div><span className="eyebrow">АСТАНА · ЕСИЛЬ</span><h2>Ваш адрес.<br/>Ваш ритм жизни.</h2><p>Первая линия на пересечении улиц Ә. Бөкейхана и Орынбор. Городская инфраструктура рядом с домом.</p><a className="button outline" href={siteUrl("/location")}>Карта инфраструктуры <ArrowUpRight size={18}/></a><a className="button blue" href={siteUrl(mapLink)} target="_blank" rel="noreferrer">Открыть в 2ГИС <ArrowUpRight size={18}/></a></div><div className="location-visual"><img src={siteUrl("/sensata/architecture.jpg")} alt="Фасад Shattyq со стороны улицы" loading="lazy"/><div><MapPin/><span>Shattyq<small>Ә. Бөкейхана / Орынбор</small></span><a href={siteUrl(mapLink)} target="_blank" rel="noreferrer" aria-label="Показать Shattyq на карте"><ArrowUpRight/></a></div></div></div>;
  return <div className={`sensata ${mode==='kiosk'?'terminal':''}`}>
    <header className="header"><a className="brand" href={siteUrl("/")} aria-label="Sensata Group — главная"><img src={siteUrl("/sensata/logo.png")} alt="Sensata Group"/></a><nav className="desktop-nav">{mode==='web'?<><details className="nav-dropdown"><summary>Квартиры</summary><div><a href={siteUrl("/visual")}>На 3D-плане</a><a href={siteUrl("/parametric-search")}>По параметрам</a><a href={siteUrl("/favorite")}>Избранное</a></div></details><details className="nav-dropdown"><summary>О проекте</summary><div>{projectLinks.slice(0,12).map(([url,title])=><a key={url} href={siteUrl(url)}>{title}</a>)}</div></details><a href={siteUrl("/audiogid")}>Аудиоэкскурсия</a><a href={siteUrl("/tour")}>3D-тур</a></>:<span className="terminal-title">SHATTYQ <span>Интерактивная презентация</span></span>}</nav><div className="header-actions"><a className="phone" href={siteUrl("tel:700")}><Phone size={17}/><strong>700</strong><span>Отдел продаж</span></a><button className="icon header-heart" onClick={showFavorites} aria-label="Открыть избранное"><Heart size={21}/>{favorites.length>0&&<b>{favorites.length}</b>}</button><button className="icon menu-button" aria-label="Открыть меню" onClick={()=>setMenu(true)}><Menu/></button><button className="button blue header-cta" onClick={goPlans}>Выбрать квартиру <ArrowUpRight size={17}/></button></div></header>
    {warning&&<div className="config-warning" role="status">{warning}</div>}
    {mode==='web'?(!isHome?<ExperienceRoutes flats={inventory} favorites={favorites} toggleFavorite={favorite} config={config} onConsult={consult}/>:<main id="top">
      <section className="hero"><img className="hero-photo" src={siteUrl("/sensata/hero.jpg")} alt="Архитектура жилого комплекса Shattyq в Астане"/><div className="hero-shade"/><div className="hero-top"><span>ПРОЕКТ SENSATA GROUP</span><span className="hero-badge">ПРЕМИУМ-КЛАСС</span></div><div className="hero-content"><span className="eyebrow">СЧАСТЬЕ БЫТЬ ДОМА</span><h1>Shattyq<span>Жизнь в гармонии с собой.</span></h1><div className="hero-bottom"><p><MapPin size={18}/>{address}</p><button className="button white" onClick={goPlans}>Найти свою квартиру <ArrowUpRight size={20}/></button></div></div><a className="hero-scroll" href={siteUrl("#about")} aria-label="Подробнее о проекте"><ArrowDown size={20}/></a></section>
      <div className="facts"><div><strong>9</strong><span>этажей</span></div><div><strong>3–4</strong><span>квартиры на этаже</span></div><div><strong>2–4</strong><span>комнаты</span></div><div><strong>24/7</strong><span>видеонаблюдение</span></div><div className="fact-note"><span>Камерный масштаб.<br/>Большое внимание к деталям.</span><ArrowUpRight/></div></div>
      <section id="about" className="section about"><div className="section-heading"><span className="eyebrow">01 / О ПРОЕКТЕ</span><h2>Больше, чем дом.<br/><span>Место для вашей жизни.</span></h2></div><div className="about-grid"><div className="about-photo"><img src={siteUrl("/sensata/architecture.jpg")} alt="Детали фасада Shattyq" loading="lazy"/><span>SHATTYQ · АСТАНА</span></div><div className="about-copy"><span className="mini-label">ПРЕМИУМ В КАЖДОЙ ДЕТАЛИ</span><h3>Личное пространство<br/>в большом городе</h3><p>Малоквартирный дом в районе Есиль: выразительная архитектура, свободные планировки и приватная территория для жизни и отдыха.</p><div className="benefits"><div><Building2/><span>Монолитный<br/>железобетонный каркас</span></div><div><Trees/><span>Закрытый двор<br/>без автомобилей</span></div><div><ScanFace/><span>Доступ в дом<br/>по Face ID</span></div><div><ShieldCheck/><span>Сквозные подъезды<br/>и видеонаблюдение</span></div></div><button className="text-link" onClick={()=>consult("Консультация по Shattyq")}>Познакомиться с проектом <ArrowUpRight size={18}/></button></div></div></section>
      <section id="gallery" className="section gallery-section"><div className="section-heading"><span className="eyebrow">02 / ПРОСТРАНСТВО</span><h2>Красота, которая<br/><span>окружает каждый день.</span></h2></div>{galleryView}</section>
      <section id="layouts" className="section layouts-section"><div className="section-heading"><span className="eyebrow">03 / ПЛАНИРОВКИ</span><h2>У каждого счастья<br/><span>своя планировка.</span></h2><p>Выберите пространство под свой образ жизни.<br/>Оригинальные планы квартир Shattyq.</p></div>{plansView}</section>
      <section className="blue-band"><span className="eyebrow">ПРОСТРАНСТВО ДЛЯ БЛИЗКИХ</span><h2>Дома — спокойно.<br/>Во дворе — счастливо.</h2><p>Зелёные прогулочные дорожки, места отдыха<br/>и закрытая территория без машин.</p><button className="button white" onClick={()=>{changeGallery('Благоустройство');document.getElementById('gallery')?.scrollIntoView({behavior:'smooth'});}}>Прогуляться по двору <ArrowUpRight size={18}/></button><img src={siteUrl("/sensata/courtyard-1.jpg")} alt="Ландшафт и детская площадка Shattyq" loading="lazy"/></section>
      <section id="location" className="section"><span className="eyebrow location-number">04 / ЛОКАЦИЯ</span>{locationView}</section>
      <HomeExperiences/><section className="contact-section" id="contacts"><div><span className="eyebrow">СЛЕДУЮЩИЙ ШАГ — ВАШ</span><h2>Давайте найдём<br/>вашу квартиру.</h2><p>Стоимость, наличие и условия покупки<br/>у команды Sensata Group.</p></div><div className="contact-action"><a href={siteUrl("tel:700")}>700 <ArrowUpRight/></a><span>Единый колл-центр · Отдел продаж</span><button className="button blue" onClick={()=>consult("Консультация по Shattyq")}>Получить консультацию <ArrowUpRight size={18}/></button></div></section>
    </main>):<main className="terminal-main"><aside className="terminal-sidebar"><span className="eyebrow">ЖИЛОЙ КОМПЛЕКС</span><h1>Shattyq</h1><span className="terminal-premium">Премиум-класс · Астана</span><nav>{[['overview','Обзор проекта',Home],['gallery','Галерея',LayoutGrid],['layouts','Планировки',Building2],['location','Локация',MapPin],['developer','О застройщике',Info]].map(([id,title,Icon])=>{const C=Icon as typeof Home;return <button key={id as string} className={section===id?'active':''} onClick={()=>setSection(id as string)}><C size={20}/>{title as string}<ArrowUpRight size={16}/></button>;})}</nav><div className="terminal-extra-links"><a href={siteUrl("/visual")}>Выбор на 3D-плане ↗</a><a href={siteUrl("/tour")}>3D-тур ↗</a><a href={siteUrl("/audiogid")}>Аудиоэкскурсия ↗</a><a href={siteUrl("/mortgage")}>Калькулятор покупки ↗</a></div><button className="button blue" onClick={()=>consult("Консультация по Shattyq")}>Связаться с нами <Phone size={17}/></button></aside><div className="terminal-content" key={section}>{section==='overview'&&<><div className="terminal-hero"><img src={siteUrl("/sensata/hero.jpg")} alt="Жилой комплекс Shattyq"/><div><span className="eyebrow">СЧАСТЬЕ БЫТЬ ДОМА</span><h2>Ваша жизнь.<br/>Ваш Shattyq.</h2><button className="button white" onClick={goPlans}>Выбрать планировку <ArrowUpRight size={18}/></button></div></div><div className="terminal-facts"><span><strong>9</strong> этажей</span><span><strong>3–4</strong> квартиры на этаже</span><span><strong>Face ID</strong> доступ в дом</span></div><p className="terminal-address"><MapPin size={18}/>{address}</p></>}{section==='gallery'&&<><h2>Галерея проекта</h2>{galleryView}</>}{section==='layouts'&&<><h2>Найдите свою планировку</h2>{plansView}</>}{section==='location'&&locationView}{section==='developer'&&<div className="developer"><img src={siteUrl("/sensata/logo.png")} alt="Sensata Group"/><h2>Дома, в которых<br/>хочется жить.</h2><p>Sensata Group — девелопер жилой недвижимости в Астане и Алматы. Shattyq — один из проектов компании в сегменте премиум.</p><a className="button blue" href={siteUrl("https://sensata.kz/ru/about")} target="_blank" rel="noreferrer">О компании <ArrowUpRight size={18}/></a></div>}</div></main>}
    <div className="prefooter-links"><a href={siteUrl("/documents/Shattyq-presentation.pdf")} download><Download size={16}/> Скачать буклет</a><a href={siteUrl("/parametric-search")}>Квартиры</a><a href={siteUrl("/tour")}>3D-тур</a><a href={siteUrl("/audiogid")}>Аудиоэкскурсия</a><a href={siteUrl("/contacts")}>Контакты</a><a href={siteUrl("/privacy")}>Конфиденциальность</a></div><footer className="footer"><img src={siteUrl("/sensata/logo-white.png")} alt="Sensata Group"/><div><span>Shattyq · Астана</span><small>Материалы проекта — <a href={siteUrl(data.source)} target="_blank" rel="noreferrer">sensata.kz <ArrowUpRight size={12}/></a></small></div><span className="footer-note">Рендеры и планировки носят информационный характер.<br/>Стоимость и наличие уточняйте в отделе продаж.</span><button className="mode-button" onClick={()=>{if(!isHome){location.assign(siteUrl('/?mode=kiosk'));return;}changeMode();}}>{mode==='web'?<Monitor size={17}/>:<Globe size={17}/>} {mode==='web'?'Режим терминала':'Веб-версия'}</button></footer>
    {menu&&<Modal close={()=>setMenu(false)} label="Навигация" wide><div className="project-menu"><div><img src={siteUrl("/sensata/logo.png")} alt="Sensata Group"/><span className="eyebrow">SHATTYQ · АСТАНА</span><h2>Счастье<br/>быть дома.</h2><a className="button blue" href={siteUrl("/visual")}>Выбрать квартиру на 3D-плане <ArrowUpRight size={17}/></a><a className="button outline" href={siteUrl("/parametric-search")}>Выбрать квартиру по параметрам</a><a className="text-link" href={siteUrl("/documents/Shattyq-presentation.pdf")} download>Скачать буклет <Download size={17}/></a></div><nav>{projectLinks.map(([url,title],i)=><a key={url} href={siteUrl(url)} onClick={()=>setMenu(false)}><span>{String(i+1).padStart(2,'0')}</span>{title}<ArrowUpRight size={17}/></a>)}</nav></div></Modal>}
    {contact&&<Modal close={()=>setContact(false)} label="Консультация по Shattyq"><LeadForm topic={contactTopic} endpoint={config.leadEndpoint}/></Modal>}
    {selected&&<Modal close={()=>setSelected(null)} label={`${selected.rooms}-комнатная планировка`} wide><div className="plan-detail"><div className={`detail-image ${zoom?'zoomed':''}`}><button onClick={()=>setZoom(v=>!v)} aria-label={zoom?'Уменьшить чертёж':'Увеличить чертёж'}><img src={siteUrl(selected.image)} alt="Оригинальный чертёж планировки Shattyq"/></button></div><div className="detail-copy"><span className="eyebrow">SHATTYQ · 1 ОЧЕРЕДЬ</span><h2>{selected.rooms}-комнатная<br/>планировка</h2><p>Вариант {selected.id.split('-')[1]?.padStart(2,'0')}</p><div className="price-info"><strong>Цена по запросу</strong><span>Актуальную стоимость и наличие уточнит менеджер.</span></div><p className="detail-note">Размеры помещений, секция и этаж указаны на оригинальном чертеже. Нажмите на план, чтобы увеличить.</p><button className="button blue" onClick={()=>{consult(`Планировка ${selected.id}: ${selected.rooms} комнаты`);setSelected(null);}}>Узнать стоимость <ArrowUpRight size={18}/></button><button className="button outline" onClick={()=>favorite(selected.id)}><Heart size={18} fill={favorites.includes(selected.id)?'currentColor':'none'}/>{favorites.includes(selected.id)?'В избранном':'Сохранить планировку'}</button><a className="text-link" href={siteUrl(`/flat/${selected.id}`)}>Полная информация о планировке <ArrowUpRight size={18}/></a><a className="text-link" href={siteUrl(selected.image)} download={`Shattyq-${selected.rooms}rooms-${selected.id}.jpg`}>Скачать чертёж <Download size={18}/></a></div></div></Modal>}
    {lightbox&&<Modal close={()=>setLightbox(false)} label={`Галерея: ${gallery}`} wide><div className="lightbox"><img src={siteUrl(galleries[gallery][slide])} alt={`${gallery} Shattyq — ${slide+1}`}/><div><button className="icon" aria-label="Предыдущее фото" onClick={()=>next(-1)}><ArrowLeft/></button><span>{gallery} · {slide+1} / {galleries[gallery].length}</span><button className="icon" aria-label="Следующее фото" onClick={()=>next(1)}><ArrowRight/></button></div></div></Modal>}
  </div>;
}

